import { assign, setup } from "xstate";
import {
  adaptationStates,
  promptMap,
  promptOptions,
  scenarioMap,
  scenarios,
  workArtefactOptions,
} from "@/lib/prototype-data";
import { evidenceLedgerMap } from "@/lib/evidence-data";
import { createId } from "@/lib/utils";
import type {
  ArtefactPayload,
  ChatMessage,
  DetailLevel,
  DocumentArtefactPayload,
  GovernanceBannerVariant,
  IntentFramingSelection,
  PresentationArtefactPayload,
  RolePersona,
  ScenarioId,
} from "@/types/prototype";

const defaultScenarioId: ScenarioId = "s1";
const defaultRolePersona: RolePersona = "new_hire";

function createWelcomeMessages(scenarioId: ScenarioId): ChatMessage[] {
  const scenario = scenarioMap[scenarioId];

  return [
    {
      id: createId("assistant"),
      role: "assistant",
      content: `${scenario.title}\n\nChoose one of the prepared prompts below. This prototype uses fixed prompts so every participant sees the same walkthrough path.`,
      meta: scenario.goal,
    },
  ];
}

function applyRoleAwareFraming({
  base,
  rolePersona,
  level,
}: {
  base: string;
  rolePersona: RolePersona;
  level: DetailLevel;
}) {
  const levelLine =
    level === "brief"
      ? "Answer style: brief and easy to scan."
      : level === "guided"
        ? "Answer style: step-by-step guidance."
        : level === "audit"
          ? "Answer style: thorough, with more reasoning and traceability."
          : "Answer style: balanced everyday explanation.";

  if (rolePersona === "manager") {
    return `Tailored for: Manager\n${levelLine}\n\n${base}\n\nManager focus: use this to discuss business impact, risk, and the next decision rather than the technical details.`;
  }

  if (rolePersona === "specialist") {
    return `Tailored for: Specialist\n${levelLine}\n\n${base}\n\nSpecialist focus: keep the wording precise and assume the reader already understands the basic domain terms.`;
  }

  return `Tailored for: New hire\n${levelLine}\n\n${base}\n\nNew-hire focus: include enough context so the reader does not need to guess why the distinction matters.`;
}

function labelFromList(list: Array<{ id: string; label: string }>, id: string) {
  return list.find((item) => item.id === id)?.label ?? id;
}

function buildSalaryOutput(selected: IntentFramingSelection) {
  const output = selected.requestedOutput;

  if (output === "email-draft") {
    return [
      "Draft reply",
      "",
      "Subject: Safe way to discuss salary patterns",
      "",
      "Hi,",
      "I can help with a broad explanation of salary patterns between roles, but I cannot share person-level salary data or details that could identify individual employees.",
      "",
      "A safe summary would focus on role families, seniority bands, and broad trends. For example, we can explain whether differences are mainly linked to role scope, market benchmarks, seniority, or responsibility level.",
      "",
      "Before this is used for any decision, HR or compliance should review the wording and confirm that the data is sufficiently aggregated.",
      "",
      "Best,",
      "Draft generated by the assistant",
    ].join("\n");
  }

  if (output === "review-note") {
    return [
      "Review note",
      "",
      "This request touches salary-related HR data. A safe response should:",
      "• use broad role or band-level patterns only;",
      "• avoid names, exact salaries, small groups, or unique combinations of details;",
      "• explain that the output is a draft, not an approved HR report;",
      "• be reviewed by HR or compliance before it is shared or used for action.",
    ].join("\n");
  }

  return [
    "Safe bullet summary",
    "",
    "• Salary differences can be discussed at role-family or seniority-band level.",
    "• Individual salaries, names, and small-group breakdowns should not be included.",
    "• The safest explanation is about patterns and possible drivers, not about individual people.",
    "• Final wording should be checked by HR or compliance before wider use.",
  ].join("\n");
}

function buildExternalSharingOutput(selected: IntentFramingSelection) {
  const output = selected.requestedOutput;

  if (output === "email-draft") {
    return [
      "Draft reply",
      "",
      "Subject: Sharing onboarding material with an external vendor",
      "",
      "Hi,",
      "Internal onboarding material may be shared with an external vendor only when there is a clear business purpose, the vendor relationship is approved, and the material has been checked against the current sharing policy.",
      "",
      "Please share only the minimum information the vendor needs. Remove internal-only notes, employee details, client-specific examples, and any content that is not approved for external use.",
      "",
      "If the material contains sensitive examples or if the approval status is unclear, ask for policy review before sending it.",
      "",
      "Best,",
      "Draft generated by the assistant",
    ].join("\n");
  }

  if (output === "review-note") {
    return [
      "Review note",
      "",
      "Before sharing onboarding material externally, check whether:",
      "• the vendor is approved for this type of collaboration;",
      "• the document is the current approved version;",
      "• internal-only notes, client examples, and personal data have been removed;",
      "• the reason for sharing is documented;",
      "• policy or compliance review is needed before sending.",
    ].join("\n");
  }

  return [
    "Policy summary",
    "",
    "• Share internal onboarding material externally only for an approved business purpose.",
    "• Use the current approved version of the material.",
    "• Share the minimum information needed for the vendor task.",
    "• Remove internal-only notes, personal details, and client-specific examples unless explicitly approved.",
    "• Ask for review when the material is sensitive or the approval status is unclear.",
  ].join("\n");
}

function buildSensitiveResponse(
  promptId: string,
  framing: IntentFramingSelection | null,
  bannerVariant: GovernanceBannerVariant | null,
) {
  const defaults = {
    goal: workArtefactOptions.intentFraming.goals[0]?.id ?? "reply-manager",
    audience: workArtefactOptions.intentFraming.audiences[0]?.id ?? "internal-manager",
    constraints: workArtefactOptions.intentFraming.constraints[0]?.id ?? "aggregate-only",
    allowedSources: workArtefactOptions.intentFraming.allowedSources[0]?.id ?? "internal-policy",
    requestedOutput: workArtefactOptions.intentFraming.requestedOutputs[0]?.id ?? "email-draft",
  };

  const selected = { ...defaults, ...(framing ?? {}) };

  const goal = labelFromList(workArtefactOptions.intentFraming.goals, selected.goal);
  const audience = labelFromList(workArtefactOptions.intentFraming.audiences, selected.audience);
  const constraints = labelFromList(workArtefactOptions.intentFraming.constraints, selected.constraints);
  const allowedSources = labelFromList(workArtefactOptions.intentFraming.allowedSources, selected.allowedSources);
  const requestedOutput = labelFromList(workArtefactOptions.intentFraming.requestedOutputs, selected.requestedOutput);

  const promptSpecific =
    promptId === "p-s2-1"
      ? {
          title: "Salary-pattern request",
          riskTrigger: "salary-related HR data",
          answer: buildSalaryOutput(selected),
        }
      : {
          title: "External-sharing request",
          riskTrigger: "internal material that may be shared outside the organisation",
          answer: buildExternalSharingOutput(selected),
        };

  const variantLabel = bannerVariant === "action" ? "warning with review step" : "warning only";

  const content = [
    `${promptSpecific.title}`,
    "",
    "Request setup used before answering:",
    `• Goal: ${goal}`,
    `• Audience: ${audience}`,
    `• Limit: ${constraints}`,
    `• Sources: ${allowedSources}`,
    `• Output: ${requestedOutput}`,
    "",
    `Why the assistant slowed down: this request touches ${promptSpecific.riskTrigger}.`,
    "",
    promptSpecific.answer,
  ].join("\n");

  const meta = `A06 request check applied · A09 ${variantLabel} · Confidence: medium · Freshness: check the latest policy before real use.`;

  return { content, meta };
}

function buildEvidenceHeavyResponse(promptId: string) {
  if (promptId === "p-s3-1") {
    return {
      content: [
        "Working answer",
        "",
        "The latest accessibility obligation is likely relevant for the customer portal, but this should still be checked against the organisation’s exact scope and the latest legal interpretation.",
        "",
        "The answer is based on three useful sources. The internal accessibility policy says customer-facing web journeys must be reviewed before release approval. The public regulation summary says the obligation applies to organisations in the covered market segment, depending on sector and size. The implementation checklist explains what teams should do next: log findings, assign owners, and review fixes before release.",
        "",
        "I did not rely on every source that was found. One older checklist was left out because it uses outdated wording. One blog-style source was left out because it overstates the rule. One legal memo could not be opened in this prototype path.",
        "",
        "Open Sources to inspect the exact fragments behind this answer.",
      ].join("\n"),
      meta: "Evidence-heavy reply · Confidence and freshness are shown inside Sources.",
    };
  }

  return {
    content: [
      "Working answer",
      "",
      "The two policy summaries are mostly aligned. They describe the same basic rule, but they place emphasis on different parts of the process.",
      "",
      "Summary A is more explicit about team-lead approval before external sharing. Summary B focuses more on documenting the reason for disclosure after approval is logged. In practice, both point to the same action: external sharing should happen only after the right approval and documentation steps are complete.",
      "",
      "I did not use every available source. An archived slide deck was left out because it exaggerates the difference between the policies. A working draft was left out because it is not approved for operational use. A department exception log could not be accessed in this prototype path.",
      "",
      "Open Sources to inspect the exact fragments behind this comparison.",
    ].join("\n"),
    meta: "Evidence-heavy reply · Confidence and freshness are shown inside Sources.",
  };
}

function buildPresentationArtefact(): PresentationArtefactPayload {
  return {
    type: "presentation",
    fileName: "executive-project-progress-draft.pptx",
    artefactLabel: "Executive project progress deck",
    slides: structuredClone(workArtefactOptions.presentation.defaultSlides),
  };
}

function buildDocumentArtefact(): DocumentArtefactPayload {
  return {
    type: "document",
    fileName: "mission-vision-values-draft.docx",
    artefactLabel: "Mission, vision, and values draft",
    pages: structuredClone(workArtefactOptions.document.defaultPages),
  };
}

function buildArtefactPayload(kind: "presentation" | "document"): ArtefactPayload {
  return kind === "presentation" ? buildPresentationArtefact() : buildDocumentArtefact();
}

function getResponseContent({
  promptId,
  level,
  rolePersona,
  framing,
  bannerVariant,
}: {
  promptId: string | null;
  level: DetailLevel;
  rolePersona: RolePersona;
  framing?: IntentFramingSelection | null;
  bannerVariant?: GovernanceBannerVariant | null;
}) {
  if (!promptId) return null;
  const prompt = promptMap[promptId];
  if (!prompt) return null;

  if (prompt.scenarioId === "s2") {
    return buildSensitiveResponse(promptId, framing ?? null, bannerVariant ?? "passive");
  }

  if (prompt.scenarioId === "s3") {
    return buildEvidenceHeavyResponse(promptId);
  }

  if (prompt.scenarioId === "s4") {
    return { content: "", meta: undefined };
  }

  const base = prompt.responses?.[level] ?? prompt.responses?.standard;
  if (!base) return null;

  if (prompt.scenarioId === "s1") {
    return {
      content: applyRoleAwareFraming({ base, rolePersona, level }),
      meta: undefined,
    };
  }

  return { content: base, meta: undefined };
}

export const studyPrototypeMachine = setup({
  types: {
    context: {} as {
      scenarioId: ScenarioId;
      selectedPromptId: string | null;
      detailLevel: DetailLevel | null;
      rolePersona: RolePersona;
      messages: ChatMessage[];
      completedPromptIds: string[];
    },
    events: {} as
      | { type: "SCENARIO.SELECT"; scenarioId: ScenarioId }
      | { type: "PROMPT.SELECT"; promptId: string }
      | { type: "DETAIL.SET"; detailLevel: DetailLevel }
      | { type: "ROLE.SET"; rolePersona: RolePersona }
      | { type: "CHAT.SEND"; framing?: IntentFramingSelection | null; bannerVariant?: GovernanceBannerVariant | null }
      | { type: "CHAT.NEXT_STEP" }
      | { type: "CHAT.RESET" },
  },
  actions: {
    selectScenario: assign(({ event, context }) => {
      if (event.type !== "SCENARIO.SELECT") return context;
      return {
        scenarioId: event.scenarioId,
        selectedPromptId: null,
        detailLevel: null,
        messages: createWelcomeMessages(event.scenarioId),
        completedPromptIds: [],
      };
    }),
    selectPrompt: assign(({ event, context }) => {
      if (event.type !== "PROMPT.SELECT") return context;
      const prompt = promptMap[event.promptId];
      if (!prompt) return context;
      return {
        selectedPromptId: prompt.id,
      };
    }),
    selectNextStep: assign(({ context }) => {
      const scenarioPrompts = promptOptions.filter((item) => item.scenarioId === context.scenarioId);
      const nextPrompt = scenarioPrompts.find((item) => !context.completedPromptIds.includes(item.id)) ?? null;
      if (!nextPrompt || nextPrompt.id === context.selectedPromptId) {
        return context;
      }
      return {
        selectedPromptId: nextPrompt.id,
      };
    }),
    setDetailLevel: assign(({ event, context }) => {
      if (event.type !== "DETAIL.SET") return context;
      return {
        detailLevel: event.detailLevel,
      };
    }),
    setRolePersona: assign(({ event, context }) => {
      if (event.type !== "ROLE.SET") return context;
      return {
        rolePersona: event.rolePersona,
      };
    }),
    sendChat: assign(({ context, event }) => {
      if (event.type !== "CHAT.SEND") return context;
      if (!context.selectedPromptId) return context;
      const prompt = promptMap[context.selectedPromptId];
      if (!prompt) return context;

      const appliedLevel: DetailLevel = context.detailLevel ?? "standard";
      const response = getResponseContent({
        promptId: context.selectedPromptId,
        level: appliedLevel,
        rolePersona: context.rolePersona,
        framing: event.framing ?? null,
        bannerVariant: event.bannerVariant ?? null,
      });
      if (!response) return context;

      const levelLabel = adaptationStates.detailLevels.find((item) => item.id === appliedLevel)?.label ?? appliedLevel;
      const roleLabel = adaptationStates.rolePersonas.find((item) => item.id === context.rolePersona)?.label ?? context.rolePersona;
      const messages: ChatMessage[] = [
        ...context.messages,
        {
          id: createId("user"),
          role: "user",
          content: prompt.prompt,
          meta: prompt.scenarioId === "s1" ? `Audience: ${roleLabel} · Detail: ${levelLabel}` : undefined,
        },
      ];

      const assistantMessage: ChatMessage = {
        id: createId("assistant"),
        role: "assistant",
        content:
          prompt.scenarioId === "s4"
            ? prompt.artefactKind === "presentation"
              ? "I created an editable presentation draft below. You can change the slide text, add or remove visuals, and download it as a PowerPoint file."
              : "I created an editable document draft below. You can change the sections, move image blocks, and download it as a Word file."
            : response.content,
        meta:
          prompt.scenarioId === "s1"
            ? `Audience used: ${roleLabel} · Detail level: ${levelLabel}`
            : prompt.scenarioId === "s4"
              ? "A05 work output editor"
              : response.meta,
      };

      if (prompt.scenarioId === "s3") {
        assistantMessage.evidence = evidenceLedgerMap[prompt.id] ?? undefined;
      }

      if (prompt.scenarioId === "s4" && prompt.artefactKind) {
        assistantMessage.artefact = buildArtefactPayload(prompt.artefactKind);
      }

      messages.push(assistantMessage);

      return {
        detailLevel: prompt.scenarioId === "s1" ? null : context.detailLevel,
        messages,
        completedPromptIds: context.completedPromptIds.includes(prompt.id)
          ? context.completedPromptIds
          : [...context.completedPromptIds, prompt.id],
      };
    }),
    resetChat: assign(({ context }) => ({
      messages: createWelcomeMessages(context.scenarioId),
      selectedPromptId: null,
      detailLevel: null,
      completedPromptIds: [],
    })),
  },
}).createMachine({
  id: "study2Prototype",
  context: {
    scenarioId: defaultScenarioId,
    selectedPromptId: null,
    detailLevel: null,
    rolePersona: defaultRolePersona,
    messages: createWelcomeMessages(defaultScenarioId),
    completedPromptIds: [],
  },
  on: {
    "SCENARIO.SELECT": { actions: "selectScenario" },
    "PROMPT.SELECT": { actions: "selectPrompt" },
    "CHAT.NEXT_STEP": { actions: "selectNextStep" },
    "DETAIL.SET": { actions: "setDetailLevel" },
    "ROLE.SET": { actions: "setRolePersona" },
    "CHAT.SEND": { actions: "sendChat" },
    "CHAT.RESET": { actions: "resetChat" },
  },
});

export const orderedScenarios = scenarios;
